/**
 * Commands Metadata — single source of truth for the help menu and list command.
 *
 * Each entry has:
 *   name     : command name used in chat (without prefix)
 *   desc     : short description shown in .list
 *   category : section header in the menu
 *   file     : filename in commands/ folder (without .js); null = always include
 *
 * Rules:
 *  - Adding a new command? Add an entry here — it auto-appears in help + list.
 *  - Any .js file in commands/ not listed here shows up under "Other".
 *  - Set `hidden: true` to keep a command out of the menus entirely.
 */

const commands = [
    // ───────────── AI ─────────────
    { name: 'gpt',        desc: 'Chat with GPT AI',                        category: 'AI',       file: 'ai' },
    { name: 'gemini',     desc: 'Chat with Google Gemini AI',              category: 'AI',       file: 'ai' },
    { name: 'imagine',    desc: 'Generate an AI image from a prompt',      category: 'AI',       file: 'imagine' },
    { name: 'flux',       desc: 'Generate image using Flux AI model',      category: 'AI',       file: 'imagine' },
    { name: 'dalle',      desc: 'Generate image using DALL-E',             category: 'AI',       file: 'imagine' },
    { name: 'sora',       desc: 'Generate image/video with Sora AI',       category: 'AI',       file: 'sora' },

    // ───────────── Download ─────────────
    { name: 'play',       desc: 'Search & play a YouTube song',            category: 'Download', file: 'play' },
    { name: 'song',       desc: 'Download YouTube audio as MP3',           category: 'Download', file: 'song' },
    { name: 'ytmp3',      desc: 'Download YouTube audio (alias)',           category: 'Download', file: 'song' },
    { name: 'mp3',        desc: 'Download YouTube audio (alias)',           category: 'Download', file: 'song' },
    { name: 'spotify',    desc: 'Download a Spotify track',                category: 'Download', file: 'spotify' },
    { name: 'instagram',  desc: 'Download Instagram post or reel',         category: 'Download', file: 'instagram' },
    { name: 'insta',      desc: 'Download Instagram media (alias)',         category: 'Download', file: 'instagram' },
    { name: 'facebook',   desc: 'Download a Facebook video',               category: 'Download', file: 'facebook' },
    { name: 'fb',         desc: 'Download Facebook video (alias)',          category: 'Download', file: 'facebook' },
    { name: 'tiktok',     desc: 'Download TikTok video (no watermark)',     category: 'Download', file: 'tiktok' },
    { name: 'tt',         desc: 'Download TikTok video (alias)',            category: 'Download', file: 'tiktok' },
    { name: 'video',      desc: 'Download a YouTube video as MP4',         category: 'Download', file: 'video' },
    { name: 'ytmp4',      desc: 'Download YouTube video as MP4 (alias)',    category: 'Download', file: 'video' },
    { name: 'gitclone',   desc: 'Download a GitHub repo as ZIP',           category: 'Download', file: 'gitclone' },
    { name: 'igs',        desc: 'Download an Instagram story',              category: 'Download', file: 'igs' },
    { name: 'igsc',       desc: 'Download Instagram story (alias)',         category: 'Download', file: 'igs' },
    { name: 'vv',         desc: 'Reveal a view-once message',               category: 'Download', file: 'viewonce' },
    { name: 'url',        desc: 'Convert media to a URL link',              category: 'Download', file: 'url' },
    { name: 'tourl',      desc: 'Convert media to URL (alias)',             category: 'Download', file: 'url' },
    { name: 'tinyurl',    desc: 'Shorten a long URL',                       category: 'Download', file: 'tinyurl' },
    { name: 'ss',         desc: 'Take a screenshot of a website',           category: 'Download', file: 'ss' },
    { name: 'ssweb',      desc: 'Screenshot a website (alias)',             category: 'Download', file: 'ss' },
    { name: 'screenshot', desc: 'Screenshot a website (alias)',             category: 'Download', file: 'ss' },

    // ───────────── Fun ─────────────
    { name: 'compliment', desc: 'Send a random compliment',                category: 'Fun',      file: 'compliment' },
    { name: 'insult',     desc: 'Send a playful insult',                    category: 'Fun',      file: 'insult' },
    { name: 'flirt',      desc: 'Send a random flirt message',             category: 'Fun',      file: 'flirt' },
    { name: 'shayari',    desc: 'Get a random Urdu/Hindi shayari poem',    category: 'Fun',      file: 'shayari' },
    { name: 'goodnight',  desc: 'Send a good night message',               category: 'Fun',      file: 'goodnight' },
    { name: 'roseday',    desc: 'Send a rose day special message',         category: 'Fun',      file: 'roseday' },
    { name: 'character',  desc: 'Generate your anime character card',       category: 'Fun',      file: 'character' },
    { name: 'ship',       desc: 'Check love % between two tagged users',   category: 'Fun',      file: 'ship' },
    { name: 'simp',       desc: 'Generate a simp card for tagged user',    category: 'Fun',      file: 'simp' },
    { name: 'stupid',     desc: 'Generate a stupid card meme',             category: 'Fun',      file: 'stupid' },
    { name: 'wasted',     desc: 'Overlay wasted effect on a photo',        category: 'Fun',      file: 'wasted' },
    { name: 'fact',       desc: 'Get a random interesting fun fact',       category: 'Fun',      file: 'fact' },
    { name: 'joke',       desc: 'Get a random funny joke',                  category: 'Fun',      file: 'joke' },
    { name: 'quote',      desc: 'Get an inspirational quote',              category: 'Fun',      file: 'quote' },
    { name: 'meme',       desc: 'Get a random meme image',                 category: 'Fun',      file: 'meme' },
    { name: 'gif',        desc: 'Search & send a GIF (type keyword)',       category: 'Fun',      file: 'gif' },
    { name: 'lyrics',     desc: 'Get lyrics for any song by name',         category: 'Fun',      file: 'lyrics' },

    // ───────────── Games ─────────────
    { name: 'tictactoe',  desc: 'Challenge someone to Tic-Tac-Toe',        category: 'Games',    file: 'tictactoe' },
    { name: 'ttt',        desc: 'Start Tic-Tac-Toe (short alias)',          category: 'Games',    file: 'tictactoe' },
    { name: 'hangman',    desc: 'Start a Hangman word guessing game',      category: 'Games',    file: 'hangman' },
    { name: 'guess',      desc: 'Guess a letter in active Hangman game',   category: 'Games',    file: 'hangman' },
    { name: 'trivia',     desc: 'Start a trivia question challenge',        category: 'Games',    file: 'trivia' },
    { name: 'answer',     desc: 'Answer the active trivia question',        category: 'Games',    file: 'trivia' },
    { name: '8ball',      desc: 'Ask the Magic 8-Ball a question',          category: 'Games',    file: 'eightball' },
    { name: 'truth',      desc: 'Get a random truth question',              category: 'Games',    file: 'truth' },
    { name: 'dare',       desc: 'Get a random dare challenge',              category: 'Games',    file: 'dare' },

    // ───────────── Group ─────────────
    { name: 'ban',        desc: 'Ban a user from using bot commands',       category: 'Group',    file: 'ban' },
    { name: 'unban',      desc: 'Remove a ban from a user',                 category: 'Group',    file: 'unban' },
    { name: 'promote',    desc: 'Promote a member to group admin',          category: 'Group',    file: 'promote' },
    { name: 'demote',     desc: 'Remove a member\'s admin privileges',      category: 'Group',    file: 'demote' },
    { name: 'mute',       desc: 'Mute group (only admins can chat)',        category: 'Group',    file: 'mute' },
    { name: 'unmute',     desc: 'Unmute the group for all members',         category: 'Group',    file: 'unmute' },
    { name: 'delete',     desc: 'Delete a replied message from group',      category: 'Group',    file: 'delete' },
    { name: 'del',        desc: 'Delete a replied message (alias)',          category: 'Group',    file: 'delete' },
    { name: 'kick',       desc: 'Remove a member from the group',           category: 'Group',    file: 'kick' },
    { name: 'warn',       desc: 'Issue a warning to a user',                category: 'Group',    file: 'warn' },
    { name: 'warnings',   desc: 'Check how many warnings a user has',       category: 'Group',    file: 'warnings' },
    { name: 'antilink',   desc: 'Enable/disable auto link removal',         category: 'Group',    file: 'antilink' },
    { name: 'antibadword', desc: 'Enable/disable bad word filter',          category: 'Group',    file: 'antibadword' },
    { name: 'antitag',    desc: 'Enable/disable anti-tag spam protection',  category: 'Group',    file: 'antitag' },
    { name: 'clear',      desc: 'Clear all messages in the group',          category: 'Group',    file: 'clear' },
    { name: 'tag',        desc: 'Tag a specific member with a message',     category: 'Group',    file: 'tag' },
    { name: 'tagall',     desc: 'Tag all members in the group at once',     category: 'Group',    file: 'tagall' },
    { name: 'tagnotadmin', desc: 'Tag all non-admin members in group',      category: 'Group',    file: 'tagnotadmin' },
    { name: 'hidetag',    desc: 'Tag all members invisibly (silent ping)',  category: 'Group',    file: 'hidetag' },
    { name: 'chatbot',    desc: 'Toggle AI chatbot auto-reply in group',    category: 'Group',    file: 'chatbot' },
    { name: 'resetlink',  desc: 'Generate a new group invite link',         category: 'Group',    file: 'resetlink' },
    { name: 'revoke',     desc: 'Reset group invite link (alias)',           category: 'Group',    file: 'resetlink' },
    { name: 'welcome',    desc: 'Enable/disable welcome messages',           category: 'Group',    file: 'welcome' },
    { name: 'goodbye',    desc: 'Enable/disable goodbye messages',           category: 'Group',    file: 'goodbye' },
    { name: 'groupinfo',  desc: 'Display full group information',            category: 'Group',    file: 'groupinfo' },
    { name: 'setgdesc',   desc: 'Change the group description',              category: 'Group',    file: 'groupmanage' },
    { name: 'setgname',   desc: 'Change the group name',                     category: 'Group',    file: 'groupmanage' },
    { name: 'setgpp',     desc: 'Change group profile photo (send photo)',   category: 'Group',    file: 'groupmanage' },
    { name: 'admins',     desc: 'List all current group administrators',     category: 'Group',    file: 'staff' },
    { name: 'staff',      desc: 'List group admins/staff (alias)',            category: 'Group',    file: 'staff' },
    { name: 'mention',    desc: 'Mention/ping a specific user in group',     category: 'Group',    file: 'mention' },
    { name: 'topmembers', desc: 'Show the most active message senders',      category: 'Group',    file: 'topmembers' },
    { name: 'antidelete', desc: 'Show deleted messages to group admins',     category: 'Group',    file: 'antidelete' },

    // ───────────── Sticker / Photo ─────────────
    { name: 'sticker',    desc: 'Convert image or video to a sticker',      category: 'Sticker',  file: 'sticker' },
    { name: 's',          desc: 'Convert to sticker (short alias)',           category: 'Sticker',  file: 'sticker' },
    { name: 'simage',     desc: 'Convert a sticker back into an image',      category: 'Sticker',  file: 'simage' },
    { name: 'attp',       desc: 'Create an animated text-to-sticker',        category: 'Sticker',  file: 'attp' },
    { name: 'removebg',   desc: 'Remove the background from a photo',        category: 'Sticker',  file: 'removebg' },
    { name: 'remini',     desc: 'AI-enhance and upscale a low-res photo',    category: 'Sticker',  file: 'remini' },
    { name: 'blur',       desc: 'Apply a blur effect to a photo',             category: 'Sticker',  file: 'img-blur' },
    { name: 'emojimix',   desc: 'Mix two emojis into one sticker',            category: 'Sticker',  file: 'emojimix' },
    { name: 'emix',       desc: 'Mix two emojis (short alias)',               category: 'Sticker',  file: 'emojimix' },
    { name: 'tgsticker',  desc: 'Download a Telegram sticker to WhatsApp',   category: 'Sticker',  file: 'stickertelegram' },
    { name: 'telesticker', desc: 'Download Telegram sticker (alias)',         category: 'Sticker',  file: 'stickertelegram' },
    { name: 'take',       desc: 'Steal and rename a sticker in chat',        category: 'Sticker',  file: 'take' },
    { name: 'steal',      desc: 'Steal and save a sticker (alias)',           category: 'Sticker',  file: 'take' },
    { name: 'crop',       desc: 'Crop a sticker into a square shape',        category: 'Sticker',  file: 'stickercrop' },
    { name: 'pies',       desc: 'Stylish country-flag themed images',        category: 'Sticker',  file: 'pies' },
    { name: 'anime',      desc: 'Get anime-themed reaction stickers',         category: 'Sticker',  file: 'anime' },

    // ───────────── Text FX ─────────────
    { name: 'metallic',   desc: 'Render text in a metallic 3D style',       category: 'Text FX',  file: 'textmaker' },
    { name: 'ice',        desc: 'Render text with an icy frozen effect',     category: 'Text FX',  file: 'textmaker' },
    { name: 'snow',       desc: 'Render text with a snowy winter style',     category: 'Text FX',  file: 'textmaker' },
    { name: 'impressive', desc: 'Render text in an impressive 3D style',     category: 'Text FX',  file: 'textmaker' },
    { name: 'matrix',     desc: 'Render text in a green matrix style',       category: 'Text FX',  file: 'textmaker' },
    { name: 'light',      desc: 'Render text with a glowing light effect',   category: 'Text FX',  file: 'textmaker' },
    { name: 'neon',       desc: 'Render text in a neon glow style',          category: 'Text FX',  file: 'textmaker' },
    { name: 'devil',      desc: 'Render text in a dark devilish style',      category: 'Text FX',  file: 'textmaker' },
    { name: 'purple',     desc: 'Render text with a purple gradient',        category: 'Text FX',  file: 'textmaker' },
    { name: 'thunder',    desc: 'Render text with lightning thunder effect', category: 'Text FX',  file: 'textmaker' },
    { name: 'leaves',     desc: 'Render text with a nature/leaves style',    category: 'Text FX',  file: 'textmaker' },
    { name: '1917',       desc: 'Render text in a vintage war film style',   category: 'Text FX',  file: 'textmaker' },
    { name: 'arena',      desc: 'Render text in a battle arena style',       category: 'Text FX',  file: 'textmaker' },
    { name: 'hacker',     desc: 'Render text in a green hacker terminal',    category: 'Text FX',  file: 'textmaker' },
    { name: 'sand',       desc: 'Render text with a sandy desert effect',    category: 'Text FX',  file: 'textmaker' },
    { name: 'blackpink',  desc: 'Render text in a BLACKPINK K-pop style',   category: 'Text FX',  file: 'textmaker' },
    { name: 'glitch',     desc: 'Render text with a digital glitch effect',  category: 'Text FX',  file: 'textmaker' },
    { name: 'fire',       desc: 'Render text engulfed in flames',            category: 'Text FX',  file: 'textmaker' },

    // ───────────── Misc ─────────────
    { name: 'heart',      desc: 'Generate a heart-shaped photo collage',    category: 'Misc',     file: 'misc' },
    { name: 'horny',      desc: 'Generate a fun horny-meter card',           category: 'Misc',     file: 'misc' },
    { name: 'circle',     desc: 'Create a circular profile photo effect',   category: 'Misc',     file: 'misc' },
    { name: 'lgbt',       desc: 'Apply a rainbow pride flag overlay',        category: 'Misc',     file: 'misc' },
    { name: 'lolice',     desc: 'Generate a fun lolice wanted card',         category: 'Misc',     file: 'misc' },
    { name: 'namecard',   desc: 'Generate a stylish name card image',        category: 'Misc',     file: 'misc' },
    { name: 'oogway',     desc: 'Get a wise Oogway quote card',              category: 'Misc',     file: 'misc' },
    { name: 'tweet',      desc: 'Generate a fake tweet image',               category: 'Misc',     file: 'misc' },

    // ───────────── General ─────────────
    { name: 'menu',       desc: 'Show the full visual help menu',            category: 'General',  file: 'help' },
    { name: 'help',       desc: 'Show the full visual help menu (alias)',    category: 'General',  file: 'help' },
    { name: 'list',       desc: 'Show all commands with descriptions',       category: 'General',  file: 'list' },
    { name: 'ping',       desc: 'Check if the bot is online and its speed', category: 'General',  file: 'ping' },
    { name: 'alive',      desc: 'Show bot uptime and status info',           category: 'General',  file: 'alive' },
    { name: 'tts',        desc: 'Convert text to speech audio',              category: 'General',  file: 'tts' },
    { name: 'owner',      desc: 'Show the bot owner\'s contact info',        category: 'General',  file: 'owner' },
    { name: 'weather',    desc: 'Get weather forecast for any city',         category: 'General',  file: 'weather' },
    { name: 'news',       desc: 'Fetch the latest news headlines',           category: 'General',  file: 'news' },
    { name: 'git',        desc: 'View the bot\'s GitHub repository',         category: 'General',  file: 'github' },
    { name: 'github',     desc: 'View the bot\'s GitHub repository (alias)', category: 'General',  file: 'github' },
    { name: 'repo',       desc: 'Open the bot source code repo (alias)',     category: 'General',  file: 'github' },
    { name: 'trt',        desc: 'Translate text to English automatically',   category: 'General',  file: 'translate' },
    { name: 'translate',  desc: 'Translate text to another language',        category: 'General',  file: 'translate' },
    { name: 'jid',        desc: 'Show your WhatsApp JID/phone number ID',   category: 'General',  file: null },
    { name: 'settings',   desc: 'View current bot settings',                 category: 'General',  file: 'settings' },
    { name: 'update',     desc: 'Check if a newer bot version is available', category: 'General',  file: 'update' },

    // ───────────── Owner ─────────────
    { name: 'mode',       desc: 'Switch between public and private mode',    category: 'Owner',    file: null },
    { name: 'autostatus', desc: 'Auto view & react to WhatsApp statuses',    category: 'Owner',    file: 'autostatus' },
    { name: 'autoread',   desc: 'Auto read and mark messages as seen',       category: 'Owner',    file: 'autoread' },
    { name: 'autotyping', desc: 'Show typing indicator for all messages',    category: 'Owner',    file: 'autotyping' },
    { name: 'autoreact',  desc: 'Automatically react to every message',      category: 'Owner',    file: null },
    { name: 'areact',     desc: 'Auto-react to messages (short alias)',       category: 'Owner',    file: null },
    { name: 'cleartmp',   desc: 'Delete all files in the temp folder',       category: 'Owner',    file: 'cleartmp' },
    { name: 'clearsession', desc: 'Remove old/inactive session files',       category: 'Owner',    file: 'clearsession' },
    { name: 'setpp',      desc: 'Change the bot\'s WhatsApp profile photo',  category: 'Owner',    file: 'setpp' },
    { name: 'anticall',   desc: 'Auto reject all incoming voice/video calls',category: 'Owner',    file: 'anticall' },
    { name: 'pmblocker',  desc: 'Block & warn unknown users in DMs',         category: 'Owner',    file: 'pmblocker' },
    { name: 'setmention', desc: 'Configure group mention settings',           category: 'Owner',    file: 'mention' },
    { name: 'sudo',       desc: 'Add or remove trusted sudo users',           category: 'Owner',    file: 'sudo' },
    { name: 'pair',       desc: 'Generate pairing code to link WhatsApp',    category: 'Owner',    file: 'pair' },
    { name: 'sessions',   desc: 'View all active user bot sessions',          category: 'Owner',    file: null },

    // ── Utility ──────────────────────────────────────────────────────────────
    { name: 'calc',      desc: 'Evaluate a math expression safely (no eval)', category: 'Utility',  file: 'calculator' },
    { name: 'qr',        desc: 'Generate a QR code image from text or URL',   category: 'Utility',  file: 'qr' },
    { name: 'profile',   desc: 'Fetch WhatsApp profile picture of any user',  category: 'Utility',  file: 'profile' },
    { name: 'password',  desc: 'Generate a cryptographically random password',category: 'Utility',  file: 'password' },
    { name: 'flip',      desc: 'Flip a coin — heads or tails',                category: 'Utility',  file: 'coinflip' },
    { name: 'dice',      desc: 'Roll an N-sided die (default: 6)',             category: 'Utility',  file: 'coinflip' },
    { name: 'roll',      desc: 'Roll multiple dice e.g. 2d6, 3d20',           category: 'Utility',  file: 'coinflip' },
    { name: 'morse',     desc: 'Encode text to Morse code',                   category: 'Utility',  file: 'morse' },
    { name: 'unmorse',   desc: 'Decode Morse code back to text',              category: 'Utility',  file: 'morse' },
    { name: 'binary',    desc: 'Convert text to binary (01010111...)',         category: 'Utility',  file: 'morse' },
    { name: 'unbinary',  desc: 'Convert binary bits back to readable text',   category: 'Utility',  file: 'morse' },
    { name: 'dadjoke',   desc: 'Get a random dad joke (API powered)',          category: 'Utility',  file: 'dadjoke' },
    { name: 'riddle',    desc: 'Random riddle — can you guess the answer?',   category: 'Utility',  file: 'dadjoke' },
    { name: 'answer',    desc: 'Reveal the answer to the current riddle',     category: 'Utility',  file: 'dadjoke' },
    { name: 'time',      desc: 'Show current time in popular world timezones',category: 'Utility',  file: 'time' },
];

// Category display config: emoji + title
const categoryConfig = {
    'AI':       { emoji: '🤖', title: 'AI Menu' },
    'Download': { emoji: '📥', title: 'Download Menu' },
    'Fun':      { emoji: '🎯', title: 'Fun Menu' },
    'Games':    { emoji: '🎮', title: 'Games Menu' },
    'Group':    { emoji: '👥', title: 'Group Menu' },
    'Sticker':  { emoji: '🎨', title: 'Sticker / Photo Menu' },
    'Text FX':  { emoji: '🔤', title: 'Text Effects Menu' },
    'Misc':     { emoji: '🧩', title: 'Misc Menu' },
    'General':  { emoji: '🌐', title: 'General Menu' },
    'Owner':    { emoji: '🔒', title: 'Owner Menu' },
    'Utility':  { emoji: '🛠️', title: 'Utility Menu' },
    'Other':    { emoji: '📦', title: 'Other Commands' },
};

module.exports = { commands, categoryConfig };
